name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build plugin
        run: npm run build

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update manifest version
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          # Update only the main Version field in manifest.json, preserving Nodejs.Version
          jq --arg version "$VERSION" '.Version = $version' \
            com.gearsdigital.betterstopwatch.sdPlugin/manifest.json > temp.json && \
            mv temp.json com.gearsdigital.betterstopwatch.sdPlugin/manifest.json

      - name: Validate plugin
        run: npx @elgato/cli validate com.gearsdigital.betterstopwatch.sdPlugin

      - name: Package plugin
        run: |
          npx @elgato/cli pack com.gearsdigital.betterstopwatch.sdPlugin \
            --no-update-check \
            --force

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: com.gearsdigital.betterstopwatch.streamDeckPlugin
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
